const play_pause_btn = document.getElementById("play-pause")
const play_btn = document.getElementsByClassName("play")
const pause_btn = document.getElementsByClassName("pause")
const stop_btn = document.getElementsByClassName("stop")
const timeline = document.getElementsByClassName("timeline")
const sound_btn = document.getElementsByClassName("sound")
const settings_btn = document.getElementsByClassName("settings")
const ecpand_btn = document.getElementsByClassName("expand")